# Generated by Django 5.1.3 on 2024-12-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('broker_name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
            ],
        ),
    ]
